name: Pull Request Labeled

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    # if: contains(github.event.pull_request.labels.*.name, 'stage')

    runs-on: ubuntu-latest

    steps:
      - name: Echo github JSON
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

